services:
  - type: worker
    name: apeittrakerbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 start.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
